Dark theme
opencode-mait/opencode-mait.github.io pull request #4
Opened 2019-09-30 16:17 UTC by Ashish0804

https://ashish0804.github.io/opencode-mait-dark-theme.github.io/index.html

2019-09-30 20:14 UTC, tm9k1 requested changes
thanks for the new PR, @Ashish0804. Please address the minor issues quickly as I see you have worked on `master` branch.
That's usually not a good thing :) . Always make a new branch from `master` when working on patches.

2019-09-30 20:14 UTC, brute4s99 commented on 404.html
> +	<p><font size=5>Oh no! Nothing here Houston! Go to <a href="index.html" alt="Go back to home page">home page</a>.</font></p>
> if it's not broken, don't fix it 

:)

2019-09-30 20:14 UTC, brute4s99 commented on about.html
> +  <p align='center'><font size=4><a href="index.html">Back to home page</a></font></p>
same as above. It works with `/`.

2019-09-30 20:14 UTC, brute4s99 commented on assets/css/main.css
> +  font-family: "Comic Sans MS", cursive, sans-serif;
Let's leave unrelated changes out of this PR.

2019-09-30 20:14 UTC, brute4s99 commented on index.html
> +        <img class="header-logo" alt="OpenCode-MAIT logo image" src="assets/img/oc_logo_t.png">
we already have `oc_logo.jpg`. Please remove the two new .PNGs as well if they are irrelevant.

2019-09-30 20:14 UTC, brute4s99 commented on index.html
> +        <li><a title='About Us' alt="About Us" href="about.html">About Us</a></li>
again, if it ain't broke, don't fix it. :)

2019-09-30 20:14 UTC, brute4s99 commented on index.html
> +                <li><a href="https://github.com/opencode-mait/coc" rel=external title='Code of Conduct' alt="Necessary for all members to follow">Code of Conduct</a></li>
same as above

2019-09-30 20:17 UTC, brute4s99 commented
Also, it'd be better to replace the pre-existing JPG with an equal-or-better quality PNG if it's about transparency. If you have problems with updating this PR, drop a message (in this PR itself) with your issue.

2019-10-01 03:37 UTC, Ashish0804 commented
@brute4s99 Thanks for the feedback, the ones where i added .html or a github link were because it wasn't redirecting properly when running locally, adding .html or index.html fixes that problem

I'll be working on the changes as suggested :)

2019-10-01 03:46 UTC, Ashish0804 commented
Okay i have made all the suggested changes but now my website hosted on my repo won't function properly since "/" takes it to the root of ashish0804.github.io rather than ashish0804.github.io/opencode-mait-dark-theme.github/index.html

Also i have kept the transparent image as without it we will see an ugly white logo in the middle of the screen.

I suggest not to change the href from the explicit link so @ me if u want me to me change it too

2019-10-01 10:28 UTC, brute4s99 commented
I cannot test your fork currently, please fix it.

2019-10-01 10:31 UTC, brute4s99 commented on index.html
> +        <li><a title='About Us' alt="About Us" href="about.html">About Us</a></li>
it works without this change

2019-10-01 10:35 UTC, Ashish0804 commented
@brute4s99 Hi
wdym u can't test? is it the problem with "back to homepage" button?

2019-10-01 10:37 UTC, brute4s99 commented
nvm, It works. Thanks for the PR, @Ashish0804. 
Merging this.

2019-10-01 10:37 UTC, merged

2019-10-01 10:38 UTC, Ashish0804 commented
thanks :)